#!/usr/bin/env python3
"""
Config-driven pipeline runner for multi-case execution.
"""

from __future__ import annotations

import argparse
import csv
import datetime
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pipeline.apartment_a_pipeline import (
    DEFAULT_APARTMENT_A_GEOMETRY_POLICY,
    DEFAULT_DXF_LAYER_PROFILE_PATH,
    DEFAULT_ROOM_PATTERN_TEXTS,
    DEFAULT_TITLE_PATTERN_TEXTS,
    DEFAULT_ZONE_OUTPUT_PREFIX,
    run_pipeline,
)
from utils import path_resolver
from utils.common import designbuilder_adiabatic_construction_name
from workspace_rules.workspace_guard import WorkspaceGuard, WorkspaceRuleError


GUARD = WorkspaceGuard(__file__)
ROOT = GUARD.root


def load_json_object(path: Path | str, *, label: str) -> dict[str, Any]:
    resolved = GUARD.assert_read_path(path)
    payload = json.loads(resolved.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise WorkspaceRuleError(f"{label} must be a JSON object: {resolved}")
    return payload


def get_path_value(payload: dict[str, Any], key: str, default: Path | str | None) -> Path | str | None:
    value = payload.get(key, default)
    if value in {None, ""}:
        return None
    return str(value)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_csv_dicts(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def collect_adiabatic_wall_targets(bundle_output_dir: Path) -> list[dict[str, str]]:
    surface_csv = bundle_output_dir / "BuildingSurface_Detailed.csv"
    if not surface_csv.is_file():
        return []
    targets = []
    for row in read_csv_dicts(surface_csv):
        if row.get("surface_type") != "Wall":
            continue
        if row.get("outside_boundary_condition") != "Adiabatic":
            continue
        source_construction = row.get("construction_name", "")
        targets.append(
            {
                "surface_name": row.get("surface_name", ""),
                "zone_name": row.get("zone_name", ""),
                "surface_type": row.get("surface_type", ""),
                "outside_boundary_condition": row.get("outside_boundary_condition", ""),
                "source_construction": source_construction,
                "target_construction": designbuilder_adiabatic_construction_name(source_construction),
            }
        )
    return targets


def write_idf_handoff_manifest(
    *,
    case_config: dict[str, Any],
    case_config_path: Path,
    result: dict[str, Any],
    case_id: str,
    geometry_project_id: str,
) -> Path:
    paths = case_config.get("paths", {})
    reports_output_dir = GUARD.resolve(
        get_path_value(paths, "reports_output_dir", None)
        or path_resolver.resolve_output_file(geometry_project_id, "reports")
    )
    path_resolver.assert_output_in_project_scope(geometry_project_id, reports_output_dir)
    GUARD.assert_write_path(reports_output_dir, allowed_roots=["5_output"], allow_create=True)
    reports_output_dir.mkdir(parents=True, exist_ok=True)

    idf_output_path = GUARD.assert_read_path(result["rebuilt_idf_output_path"])
    bundle_output_dir = GUARD.assert_read_path(result["bundle_output_dir"])
    adiabatic_wall_targets = collect_adiabatic_wall_targets(bundle_output_dir)
    target_constructions = sorted({row["target_construction"] for row in adiabatic_wall_targets if row["target_construction"]})
    manifest = {
        "manifest_type": "idf_handoff",
        "manifest_version": 1,
        "created_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "case_id": case_id,
        "geometry_project_id": geometry_project_id,
        "model_id": str(case_config.get("model_id", "")).strip(),
        "case_name": str(case_config.get("case_name", "")).strip(),
        "case_config_path": str(case_config_path.relative_to(ROOT)).replace("\\", "/"),
        "idf_output_path": str(idf_output_path.relative_to(ROOT)).replace("\\", "/"),
        "idf_sha256": sha256_file(idf_output_path),
        "bundle_output_dir": str(bundle_output_dir.relative_to(ROOT)).replace("\\", "/"),
        "adiabatic_wall_count": len(adiabatic_wall_targets),
        "adiabatic_target_constructions": target_constructions,
        "adiabatic_wall_targets": adiabatic_wall_targets,
        "qa_status": "NOT_RUN_BY_PIPELINE",
        "notes": [
            "This manifest is generated by DesignBuilder_DXF_to_IDF_Pipeline after rebuilding the IDF.",
            "Script workspace should copy this manifest and the IDF into the active run generated folder before DesignBuilder import/simulation.",
        ],
    }
    output_path = reports_output_dir / "idf_handoff_manifest.json"
    GUARD.assert_write_path(output_path, allowed_roots=["5_output"], allow_create=True, allow_overwrite=True)
    output_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    return output_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Run a configured case pipeline.")
    parser.add_argument(
        "--case-config",
        default=None,
        help="Optional path to pipeline_case.json. If omitted, resolves from 2_config/projects/<project_id>/pipeline_case.json.",
    )
    parser.add_argument(
        "--project",
        default=None,
        help="Project ID to run. If omitted, reads 2_config/default_project.json.",
    )
    parser.add_argument(
        "--ceiling-height-m",
        type=float,
        required=True,
        help="Human-provided zone/model ceiling height in meters for this build.",
    )
    args = parser.parse_args()

    resolved_project_id = path_resolver.resolve_project_id(args.project) if args.case_config is None else None
    case_config_candidate = (
        args.case_config
        or ROOT / "2_config" / "projects" / resolved_project_id / "pipeline_case.json"
    )
    case_config_path = GUARD.assert_read_path(case_config_candidate)
    case_config = load_json_object(case_config_path, label="Case config")

    case_id = str(case_config.get("case_id", "")).strip()
    if not case_id:
        raise WorkspaceRuleError(f"Case config is missing case_id: {case_config_path}")
    geometry_project_id = str(case_config.get("geometry_project_id", "") or resolved_project_id or case_id).strip()
    if not geometry_project_id:
        raise WorkspaceRuleError(f"Case config is missing geometry_project_id: {case_config_path}")

    paths = case_config.get("paths", {})
    if not isinstance(paths, dict):
        raise WorkspaceRuleError(f"Case config paths must be an object: {case_config_path}")

    options = case_config.get("options", {})
    if not isinstance(options, dict):
        raise WorkspaceRuleError(f"Case config options must be an object: {case_config_path}")

    config_files = case_config.get("config_files", {})
    if not isinstance(config_files, dict):
        raise WorkspaceRuleError(f"Case config config_files must be an object: {case_config_path}")

    geometry_policy_path = get_path_value(
        config_files,
        "geometry_policy",
        DEFAULT_APARTMENT_A_GEOMETRY_POLICY,
    )
    layer_profile_path = get_path_value(config_files, "dxf_layer_profile", DEFAULT_DXF_LAYER_PROFILE_PATH)
    naming_rules_path = get_path_value(config_files, "naming_rules", None)
    naming_rules: dict[str, Any] = {}
    if naming_rules_path is not None:
        naming_rules = load_json_object(naming_rules_path, label="Naming rules")

    room_pattern_texts = list(naming_rules.get("room_anchor_patterns", list(DEFAULT_ROOM_PATTERN_TEXTS)))
    title_pattern_texts = list(naming_rules.get("title_anchor_patterns", list(DEFAULT_TITLE_PATTERN_TEXTS)))
    zone_output_prefix = str(naming_rules.get("zone_output_prefix", DEFAULT_ZONE_OUTPUT_PREFIX))
    object_output_prefix = str(naming_rules.get("object_output_prefix", "") or "").strip().rstrip("_")

    result = run_pipeline(
        project_id=geometry_project_id,
        input_path=get_path_value(paths, "dxf_input", None),
        output_path=get_path_value(paths, "extract_output", None),
        schema_output_path=get_path_value(paths, "schema_output", None),
        mapping_output_path=get_path_value(paths, "mapping_output", None),
        mapping_output_dir=get_path_value(paths, "mapping_output_dir", None),
        idf_bundle_output_dir=get_path_value(paths, "bundle_output_dir", None),
        rebuilt_idf_output_path=get_path_value(paths, "rebuilt_idf_output", None),
        padding=float(options.get("padding", 2500.0) or 2500.0),
        room_pattern_texts=room_pattern_texts,
        title_pattern_texts=title_pattern_texts,
        geometry_policy_path=geometry_policy_path or DEFAULT_APARTMENT_A_GEOMETRY_POLICY,
        ceiling_height_m=args.ceiling_height_m,
        layer_profile_path=layer_profile_path or DEFAULT_DXF_LAYER_PROFILE_PATH,
        zone_output_prefix=zone_output_prefix,
        object_output_prefix=object_output_prefix,
        dxf_normalized_output_dir=get_path_value(paths, "dxf_normalized_output_dir", None),
        geometry_output_dir=get_path_value(paths, "geometry_output_dir", None),
        surface_output_dir=get_path_value(paths, "surface_output_dir", None),
        wall_output_dir=get_path_value(paths, "wall_output_dir", None),
        fenestration_output_dir=get_path_value(paths, "fenestration_output_dir", None),
    )
    manifest_path = write_idf_handoff_manifest(
        case_config=case_config,
        case_config_path=case_config_path,
        result=result,
        case_id=case_id,
        geometry_project_id=geometry_project_id,
    )

    print("CASE_PIPELINE_COMPLETE")
    print(f"Case: {case_id}")
    print(f"Geometry project: {geometry_project_id}")
    print(f"Case config: {case_config_path.relative_to(ROOT)}")
    print(f"Extract output: {Path(result['extract_output_path']).relative_to(ROOT)}")
    if result.get("bundle_output_dir") is not None:
        print(f"Bundle output: {Path(result['bundle_output_dir']).relative_to(ROOT)}")
    if result.get("rebuilt_idf_output_path") is not None:
        print(f"Rebuilt IDF: {Path(result['rebuilt_idf_output_path']).relative_to(ROOT)}")
    print(f"Handoff manifest: {manifest_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
